M48
; DRILL file {KiCad (7.0.0)} date Fri Dec  8 18:55:45 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-08T18:55:45+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.2913Y-2.9134
X4.6063Y-4.4882
X6.8504Y-2.9134
X6.8504Y-4.4882
T0
M30
